/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lovef1st_ (https://sketchfab.com/lovef1st_)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bucket-hat-293440f8d77549b8a99d0ca6ca8ba614
title: Bucket Hat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BucketHat({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bucket_hat/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={2}>
            <mesh geometry={nodes.Sphere_Material_0.geometry} material={materials.Material} material-color={'hotpink'} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/backet_hat/scene.gltf')
