/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cap({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cap/cap.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={1.5}>
      <mesh geometry={nodes.Crown.geometry} material={materials['Material.001']} material-color={props.customColors.crown} />
      <mesh geometry={nodes.Cape.geometry} material={materials['Material.004']} material-color={props.customColors.cape} />
      <mesh geometry={nodes.Visor.geometry} material={materials['Material.002']} material-color={props.customColors.visor} />
      <mesh geometry={nodes.Top_point.geometry} material={materials['Material.003']} position={[0, 0.93, 0]} scale={[0.04, 0.02, 0.04]} material-color={props.customColors.topPoint}/>
    </group>
  )
}

useGLTF.preload('/cap/cap.gltf')
